-- MySQL Script generated by MySQL Workbench
-- Sun Jun 11 15:12:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Asignamos privilegios para los metodos de verificación de la base de datos
-- COMANDOS A EJECUTAR PARA LOS PERMISOS DE LA BASE DE DATOS Y LA API
-- ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Francisco1999';
-- flush privileges;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MEXCOM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MEXCOM`;

CREATE DATABASE MEXCOM;
-- -----------------------------------------------------
-- Schema MEXCOM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MEXCOM` DEFAULT CHARACTER SET utf8 ;
USE `MEXCOM` ;

-- -----------------------------------------------------
-- Table `MEXCOM`.`Fotografias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Fotografias` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `fotografia` BLOB,
  PRIMARY KEY (`idFoto`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idFoto_UNIQUE` ON `MEXCOM`.`Fotografias` (`idFoto` ASC) VISIBLE;

INSERT INTO `MEXCOM`.`Fotografias`(`idFoto`)
VALUES(1);
-- -----------------------------------------------------
-- Table `MEXCOM`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `idFoto` INT,
  `nombreAdministrador` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`, `idFoto`),
  CONSTRAINT `idFoto`
    FOREIGN KEY (`idFoto`)
    REFERENCES `MEXCOM`.`Fotografias` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Usuario_UNIQUE` ON `MEXCOM`.`Administrador` (`nombreAdministrador` ASC) VISIBLE;
CREATE UNIQUE INDEX `Correo electronico_UNIQUE` ON `MEXCOM`.`Administrador` (`correoElectronico` ASC) VISIBLE;
CREATE UNIQUE INDEX `idAdministrador_UNIQUE` ON `MEXCOM`.`Administrador` (`idAdministrador` ASC) VISIBLE;

CREATE INDEX `idFoto_idx` ON `MEXCOM`.`Administrador` (`idFoto` ASC) VISIBLE;

-- Insertamos un usuario administrador de ejemplo
INSERT INTO `MEXCOM`.`Administrador` (`idFoto`, `nombreAdministrador`, `correoElectronico`, `contraseña`) 
VALUES (1, 'Juan Perez', 'juan@example.com', 'secreto123');

-- -----------------------------------------------------
-- Table `MEXCOM`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Estados` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombreEstado` VARCHAR(45) NOT NULL,
  `cantidadRegiones` INT NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


CREATE UNIQUE INDEX `idEstado_UNIQUE` ON `MEXCOM`.`Estados` (`idEstado` ASC) VISIBLE;
CREATE UNIQUE INDEX `nombre_Estado_UNIQUE` ON `MEXCOM`.`Estados` (`nombreEstado` ASC) VISIBLE;

-- Insertamos un estado 
INSERT INTO `MEXCOM`.`Estados` (`nombreEstado`, `cantidadRegiones`) 
VALUES ('Ciudad de Mexico', 0);

-- -----------------------------------------------------
-- Table `MEXCOM`.`Municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Municipios` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `idEstado` INT NOT NULL,
  `nombreMunicipio` VARCHAR(45) NOT NULL,
  `cantidadRegiones` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`, `idEstado`),
  CONSTRAINT `idEstado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `MEXCOM`.`Estados` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMunicipio_UNIQUE` ON `MEXCOM`.`Municipios` (`idMunicipio` ASC) VISIBLE;
CREATE INDEX `idEstado_idx` ON `MEXCOM`.`Municipios` (`idEstado` ASC) VISIBLE;

-- Insertamos un Municipio 
INSERT INTO `MEXCOM`.`Municipios` (`idEstado`, `nombreMunicipio` ,`cantidadRegiones`) 
VALUES (1, "Gustavo A. Madero", 0);

-- -----------------------------------------------------
-- Table `MEXCOM`.`Localidadades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Localidadades` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `idMunicipio` INT NOT NULL,
  `nombreLocalidad` VARCHAR(45) NOT NULL,
  `cantidadRegiones` INT NOT NULL,
  PRIMARY KEY (`idLocalidad`, `idMunicipio`),
  CONSTRAINT `idMunipio`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `MEXCOM`.`Municipios` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idMunipio_idx` ON `MEXCOM`.`Localidadades` (`idMunicipio` ASC) VISIBLE;

-- Insertamos datos de la localidad lindavista
INSERT INTO `MEXCOM`.`Localidadades` (`idMunicipio`, `nombreLocalidad`, `cantidadRegiones`)
VALUES(1, "Lindavista", 0);

-- -----------------------------------------------------
-- Table `MEXCOM`.`Colonias_Barrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Colonias_Barrios` (
  `idColonia` INT NOT NULL AUTO_INCREMENT,
  `idLocalidad` INT NOT NULL,
  `nombreColonia` VARCHAR(45) NOT NULL,
  `cantidadRegiones` INT NOT NULL,
  PRIMARY KEY (`idColonia`, `idLocalidad`),
  CONSTRAINT `idLocalidad`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `MEXCOM`.`Localidadades` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idColonias_UNIQUE` ON `MEXCOM`.`Colonias_Barrios` (`idColonia` ASC) VISIBLE;
CREATE INDEX `idLocalidad_idx` ON `MEXCOM`.`Colonias_Barrios` (`idLocalidad` ASC) VISIBLE;

-- Insertamos datos de la localidad lindavista
INSERT INTO `MEXCOM`.`Colonias_Barrios` (`idLocalidad`, `nombreColonia`, `cantidadRegiones`)
VALUES(1, "Zacatenco", 0);

-- -----------------------------------------------------
-- Table `MEXCOM`.`Regiónes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Regiónes` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `idColonia` INT NOT NULL,
  `nombreRegión` VARCHAR(45) NOT NULL,
  `cantidadOfertantes` INT NOT NULL,
  `geoJSON` GEOMETRY,
  PRIMARY KEY (`idRegion`, `idColonia`),
  CONSTRAINT `idColonia`
    FOREIGN KEY (`idColonia`)
    REFERENCES `MEXCOM`.`Colonias_Barrios` (`idColonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idRegiones_UNIQUE` ON `MEXCOM`.`Regiónes` (`idRegion` ASC) VISIBLE;
CREATE INDEX `idColonia_idx` ON `MEXCOM`.`Regiónes` (`idColonia` ASC) VISIBLE;

-- ``
INSERT INTO `MEXCOM`.`Regiónes` (`idColonia`, `nombreRegión`, `cantidadOfertantes`)
VALUES(1, "ESCOM", 5);



-- -----------------------------------------------------
-- Table `MEXCOM`.`Ofertadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Ofertadores` (
  `idOfertador` INT NOT NULL AUTO_INCREMENT,
  `idFoto` INT,
  `tipoOfertador` VARCHAR(18) NOT NULL,
  `nombreOfertante` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `informacionContacto` VARCHAR(100) NULL,
  PRIMARY KEY (`idOfertador`, `idFoto`),
  CONSTRAINT `FK_Ofertadores_Fotografias`
    FOREIGN KEY (`idFoto`)
    REFERENCES `MEXCOM`.`Fotografias` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProvedorDeServicios_UNIQUE` ON `MEXCOM`.`Ofertadores` (`idOfertador` ASC) VISIBLE;
CREATE UNIQUE INDEX `nombreProvedor_UNIQUE` ON `MEXCOM`.`Ofertadores` (`nombreOfertante` ASC) VISIBLE;
CREATE INDEX `idFoto_idx` ON `MEXCOM`.`Ofertadores` (`idFoto` ASC) VISIBLE;

-- Resto de las instrucciones INSERT...

-- Insertamos algunos ofertantes como ejemplos
INSERT INTO `MEXCOM`.`Ofertadores` (`idFoto`, `tipoOfertador`, `nombreOfertante`, `fechaNacimiento`, `usuario`, `contraseña`, `correoElectronico`, `informacionContacto`)
VALUES (1, 'Comerciante', 'Juan Pérez', '1990-01-01', 'juanperez', '123456', 'juan@example.com', 'Whastapp: 5594685215');

INSERT INTO `MEXCOM`.`Ofertadores` (`idFoto`, `tipoOfertador`, `nombreOfertante`, `fechaNacimiento`, `usuario`, `contraseña`, `correoElectronico`, `informacionContacto`)
VALUES (1, 'Comerciante', 'Pedro Ramírez', '1995-09-20', 'pedroramirez', 'qwerty', 'pedro@example.com', 'Facebook: Miguel Reparalo');

INSERT INTO `MEXCOM`.`Ofertadores` (`idFoto`, `tipoOfertador`, `nombreOfertante`, `fechaNacimiento`, `usuario`, `contraseña`, `correoElectronico`, `informacionContacto`)
VALUES (1, 'ProveedorServicios', 'María López', '1985-05-10', 'marialopez', 'abcdef', 'maria@example.com', 'Telefono: 5596034295');

INSERT INTO `MEXCOM`.`Ofertadores` (`idFoto`, `tipoOfertador`, `nombreOfertante`, `fechaNacimiento`, `usuario`, `contraseña`, `correoElectronico`, `informacionContacto`)
VALUES (1, 'Comerciante', 'Luis González', '1988-12-15', 'luisgonzalez', '7890', 'luis@example.com', NULL);

INSERT INTO `MEXCOM`.`Ofertadores` (`idFoto`, `tipoOfertador`, `nombreOfertante`, `fechaNacimiento`, `usuario`, `contraseña`, `correoElectronico`, `informacionContacto`)
VALUES (1, 'ProveedorServicios', 'Ana Torres', '1993-06-25', 'anatorres', 'EscomServicios19823', 'ana@example.com', 'Correo electronico de contacto: AsesoriasEscom@hotmail.com');



-- -----------------------------------------------------
-- Table `MEXCOM`.`puntosDeOferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`puntosDeOferta` (
  `idPuntoDeOferta` INT NOT NULL AUTO_INCREMENT,
  `idRegion` INT NOT NULL,
  `idOfertador` INT NOT NULL,
  `idFoto` INT NOT NULL,
  `nombrePuntoDeOferta` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(250) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPuntoDeOferta`, `idRegion`, `idOfertador`, `idFoto`),
  CONSTRAINT `FK_puntosDeOferta_Regiones`
    FOREIGN KEY (`idRegion`)
    REFERENCES `MEXCOM`.`Regiónes` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_puntosDeOferta_Ofertadores`
    FOREIGN KEY (`idOfertador`)
    REFERENCES `MEXCOM`.`Ofertadores` (`idOfertador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_puntosDeOferta_Fotografias`
    FOREIGN KEY (`idFoto`)
    REFERENCES `MEXCOM`.`Fotografias` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE UNIQUE INDEX `idpuntosDeOferta_UNIQUE` ON `MEXCOM`.`puntosDeOferta` (`idPuntoDeOferta` ASC) VISIBLE;
CREATE INDEX `idRegion_idx` ON `MEXCOM`.`puntosDeOferta` (`idRegion` ASC) VISIBLE;
CREATE INDEX `idOfertador_idx` ON `MEXCOM`.`puntosDeOferta` (`idOfertador` ASC) VISIBLE;
CREATE INDEX `idFoto_idx` ON `MEXCOM`.`puntosDeOferta` (`idFoto` ASC) VISIBLE;

INSERT INTO `MEXCOM`.`puntosDeOferta` (`idRegion`, `idOfertador`, `idFoto`, `nombrePuntoDeOferta`, `descripción`, `horario`)
VALUES (1, 1, 1, 'Comida COTSCO', 'Alimentos ricos recién traídos de COTSCO', 'Lunes a viernes: 12:00 PM - 8:00 PM');

INSERT INTO `MEXCOM`.`puntosDeOferta` (`idRegion`, `idOfertador`, `idFoto`, `nombrePuntoDeOferta`, `descripción`, `horario`)
VALUES (1, 3, 1, 'Asesoría en computación', 'Ofrezco asesorías en programación en diversas áreas', 'Martes y jueves: 6:00 PM - 7:30 PM');

INSERT INTO `MEXCOM`.`puntosDeOferta` (`idRegion`, `idOfertador`, `idFoto`, `nombrePuntoDeOferta`, `descripción`, `horario`)
VALUES (1, 5, 1, 'Servicios de Reparación Mike', 'Ofrezco mis servicios de reparación y mantenimiento de dispositivos electrónicos', 'Lunes a viernes: 8:00 AM - 6:00 PM');

INSERT INTO `MEXCOM`.`puntosDeOferta` (`idRegion`, `idOfertador`, `idFoto`, `nombrePuntoDeOferta`, `descripción`, `horario`)
VALUES (4, 2, 1, 'Accesorios y más Yuly', 'Venta de los mejores accesorios y stickers en ESCOM', 'Lunes a domingo: 9:00 AM - 6:00 PM');

INSERT INTO `MEXCOM`.`puntosDeOferta` (`idRegion`, `idOfertador`, `idFoto`, `nombrePuntoDeOferta`, `descripción`, `horario`)
VALUES (1, 4, 1, 'Dulces Escom', 'Venta de variedad de dulces y jugos - Servicio hasta su salón', 'Lunes a domingo: 6:00 PM - 10:00 PM');

-- -----------------------------------------------------
-- Table `MEXCOM`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `idPuntoDeOferta` INT NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(300) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idProducto`, `idPuntoDeOferta`),
  CONSTRAINT `idPuntoDeOferta`
    FOREIGN KEY (`idPuntoDeOferta`)
    REFERENCES `MEXCOM`.`puntosDeOferta` (`idPuntoDeOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProductos_UNIQUE` ON `MEXCOM`.`Productos` (`idProducto` ASC) VISIBLE;
CREATE UNIQUE INDEX `nombreProducto_UNIQUE` ON `MEXCOM`.`Productos` (`nombreProducto` ASC) VISIBLE;
CREATE INDEX `idPuntoDeOferta_idx` ON `MEXCOM`.`Productos` (`idPuntoDeOferta` ASC) VISIBLE;


-- Valores por defecto para los productos del primer vendedor
INSERT INTO `MEXCOM`.`Productos` (`idPuntoDeOferta`, `nombreProducto`, `descripción`, `precio`)
VALUES (1, 'Galletas de Chocolate', 'Deliciosas galletas de chocolate con trozos de chocolate semiamargo', 25.99);
INSERT INTO `MEXCOM`.`Productos` (`idPuntoDeOferta`, `nombreProducto`, `descripción`, `precio`)
VALUES (1, 'Rebanadas de Pizza', 'Pizza recién horneada con variedad de ingredientes y sabores', 45.99);
INSERT INTO `MEXCOM`.`Productos` (`idPuntoDeOferta`, `nombreProducto`, `descripción`, `precio`)
VALUES (1, 'Chicken Roll', 'Rollos de pollo crujiente y jugoso con especias y salsas', 35.99);


-- -----------------------------------------------------
-- Table `MEXCOM`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`Servicios` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `idPuntoDeOferta` INT NOT NULL,
  `nombreServicio` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(300) NOT NULL,
  `precioAproximado(Minimo)` INT NOT NULL,
  `precioAproximado(Maximo)` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `idPuntoDeOferta`),
  CONSTRAINT `idPuntoDeOferta0`
    FOREIGN KEY (`idPuntoDeOferta`)
    REFERENCES `MEXCOM`.`puntosDeOferta` (`idPuntoDeOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProductos_UNIQUE` ON `MEXCOM`.`Servicios` (`idServicio` ASC) VISIBLE;
CREATE UNIQUE INDEX `nombreProducto_UNIQUE` ON `MEXCOM`.`Servicios` (`nombreServicio` ASC) VISIBLE;
CREATE INDEX `idPuntoDeOferta_idx` ON `MEXCOM`.`Servicios` (`idPuntoDeOferta` ASC) VISIBLE;

-- Valores para pruebas de servicios
INSERT INTO `MEXCOM`.`Servicios` (`idPuntoDeOferta`, `nombreServicio`, `descripción`, `precioAproximado(Minimo)`, `precioAproximado(Maximo)`)
VALUES (3, 'Reparación de Pantalla', 'Servicio de reparación de pantallas de dispositivos electrónicos como teléfonos, tablets y televisores.', 300, 800);
INSERT INTO `MEXCOM`.`Servicios` (`idPuntoDeOferta`, `nombreServicio`, `descripción`, `precioAproximado(Minimo)`, `precioAproximado(Maximo)`)
VALUES (3, 'Reparación de Computadoras', 'Servicio de reparación y mantenimiento de computadoras de escritorio y portátiles.', 500, 1500);
INSERT INTO `MEXCOM`.`Servicios` (`idPuntoDeOferta`, `nombreServicio`, `descripción`, `precioAproximado(Minimo)`, `precioAproximado(Maximo)`)
VALUES (3, 'Reparación de Controles de Xbox', 'Servicio de reparación de controles de Xbox, incluyendo reparación de botones, sticks analógicos y conexiones inalámbricas.', 100, 300);

-- -----------------------------------------------------
-- Table `MEXCOM`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`review` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `idPuntoDeOferta` INT NOT NULL,
  `puntuacionPromedio` INT NULL,
  PRIMARY KEY (`idReview`, `idPuntoDeOferta`)
)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idreseñas_UNIQUE` ON `MEXCOM`.`review` (`idReview` ASC) VISIBLE;
CREATE INDEX `idPuntoDeOferta_idx` ON `MEXCOM`.`review` (`idPuntoDeOferta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MEXCOM`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEXCOM`.`comentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idReview` INT NOT NULL,
  `idFoto` INT,
  `comentario` VARCHAR(100) NOT NULL,
  `puntuacionPositiva` INT NULL,
  `puntuacionNegativa` INT NULL,
  PRIMARY KEY (`idComentario`, `idReview`, `idFoto`),
  CONSTRAINT `idReview`
    FOREIGN KEY (`idReview`)
    REFERENCES `MEXCOM`.`review` (`idReview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcomentarios_UNIQUE` ON `MEXCOM`.`comentarios` (`idComentario` ASC) VISIBLE;
CREATE INDEX `idReview_idx` ON `MEXCOM`.`comentarios` (`idReview` ASC) VISIBLE;


-- Opiniones de personas para las reparaciones mike
INSERT INTO `MEXCOM`.`comentarios` (`idReview`, `idFoto`, `comentario`, `puntuacionPositiva`, `puntuacionNegativa`)
VALUES (1, 1, 'No me gusto mucho el servicio de reparación de pantalla no tuvieron mucho cuidado con mi teléfono', 10, NULL);

INSERT INTO `MEXCOM`.`comentarios` (`idReview`, `idFoto`, `comentario`, `puntuacionPositiva`, `puntuacionNegativa`)
VALUES (1, 1, 'El servicio de reparación de computadoras es muy profesional y rápido.', 9, NULL);

INSERT INTO `MEXCOM`.`comentarios` (`idReview`, `idFoto`, `comentario`, `puntuacionPositiva`, `puntuacionNegativa`)
VALUES (1, 1, 'Repararon mi control de Xbox en tiempo récord, quedó funcionando perfectamente.', 8, NULL);

INSERT INTO `MEXCOM`.`comentarios` (`idReview`, `idFoto`, `comentario`, `puntuacionPositiva`, `puntuacionNegativa`)
VALUES (1, 1, 'El servicio de reparación de televisores es muy recomendable, solucionaron el problema rápidamente.', 9, NULL);

INSERT INTO `MEXCOM`.`comentarios` (`idReview`, `idFoto`, `comentario`, `puntuacionPositiva`, `puntuacionNegativa`)
VALUES (1, 1, 'La reparación de mi laptop fue impecable, los técnicos son muy conocedores.', 10, NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
